/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./src/qa-portal/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Inter"', 'system-ui', 'sans-serif'],
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        background: '#F7F3F0',
        'on-background': '#1A1A1A',
        surface: '#ffffff',
        'surface-dim': '#E6E1DC',
        'surface-bright': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#FAF8F6',
        'surface-container': '#F3ECE7',
        'surface-container-high': '#EAE3DD',
        'surface-container-highest': '#DFD4CA',
        'on-surface': '#1A1A1A',
        'on-surface-variant': '#5C5854',
        'inverse-surface': '#1A1A1A',
        'inverse-on-surface': '#F7F3F0',
        outline: '#8B7E66',
        'outline-variant': 'rgba(26, 26, 26, 0.1)',
        'surface-tint': '#8B7E66',
        primary: '#1A1A1A',
        'on-primary': '#F7F3F0',
        'primary-container': '#F3ECE7',
        'on-primary-container': '#8B7E66',
        'inverse-primary': '#8B7E66',
        secondary: '#8B7E66',
        'on-secondary': '#ffffff',
        'secondary-container': '#FAF8F6',
        'on-secondary-container': '#1A1A1A',
        tertiary: '#8B7E66',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#F3ECE7',
        'on-tertiary-container': '#8B7E66',
        error: '#A34E36',
        'on-error': '#ffffff',
        'error-container': '#F9EAE6',
        'on-error-container': '#A34E36',
      },
    },
  },
  plugins: [],
}
